version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
install:
  # force to use msbuild 15.0 the path as VS2013 solutions uses msbuild 12.0 
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\15.0\Bin;%PATH%
before_build:
  # restore nuget
  - nuget restore
after_build:
    - ps: if($env:appveyor_repo_tag -eq 'True') { nuget pack .\SPIClient\SPIClient.csproj -IncludeReferencedProjects -OutputDirectory artifacts }
    - dir
configuration:
  - Release  
artifacts:
  - path: '.\artifacts\**\*.nupkg'
deploy:
  provider: NuGet
  api_key: 
    secure: DPV1xq+HlBCg2gaAhal/egR1Nrxefde1jPxieommNG7BkXkzRtOpnTyoIZS/nAyL  
